spring:
  application:
    name: panama-canal
  datasource:
    url: jdbc:sqlite:memory:myDb?cache=shared
    #    url: jdbc:sqlite:./data/mydatabase.db
    driverClassName: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/myrealm

logging:
  level:
    org:
      hibernate:
        SQL: debug