spring:
  application:
    name: panama-canal
  datasource:
    url: jdbc:sqlite:./data/panama.db?cache=shared
    driverClassName: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/myrealm
          jwk-set-uri: http://localhost:18080/realms/myrealm/protocol/openid-connect/certs

logging:
  level:
    org:
      hibernate:
        SQL: debug